### ISSUE TITLE
xdg_config_home typo

### ISSUE THREAD

**Issue by leoniloris** [de-vri-es/setup-git-credentials#1]
It has a possible typo here 
https://github.com/fusion-engineering/setup-git-credentials/blob/master/src/main.ts#L9
XGD or XDG?

**Comment by m-ou-se** [comment]
Yes, thanks!

**Comment by m-ou-se** [comment]
Published as v2.0.1.

**Comment by m-ou-se** [comment]
Oops, looks like I messed something up. @de-vri-es can you take a look?
