### ISSUE TITLE
Credentials in some cases are appended without newline

### ISSUE THREAD

**Issue by leynebe** [de-vri-es/setup-git-credentials#11]
I had an issue with the action today where lines to the `.config/git/credentials` were appended without newline.

Example:
```
https://foo:REMOVED_SECRET@github.comhttps://foo:REMOVED_SECRET@github.comhttps://foo:REMOVED_SECRET@github.comhttps://foo:REMOVED_SECRET@github.comhttps://foo:REMOVED_SECRET@github.comhttps://foo:REMOVED_SECRET@github.comhttps://foo:REMOVED_SECRET@github.comhttps://foo:REMOVED_SECRET@github.comhttps://foo:REMOVED_SECRET@github.comhttps://foo:REMOVED_SECRET@github.comhttps://foo:REMOVED_SECRET@github.comhttps://foo:REMOVED_SECRET@github.comhttps://foo:REMOVED_SECRET@github.com
```

I'm using:
* A self-hosted runner running Amazon Linux 2
* setup-git-credentials v2.0.6

I solved it by removing the credentials file and re-running the ci, for some reason this time it decided to add newlines, but I have no idea why and what is the cause of this.

```
https://foo:REMOVED_SECRET@github.com
https://foo:REMOVED_SECRET@github.com
```

I can provide more info if needed, let me know.

**Comment by de-vri-es** [comment]
> I solved it by removing the credentials file and re-running the ci, for some reason this time it decided to add newlines, but I have no idea why and what is the cause of this.

Do you mean you removed the github secret and re-created it? I can't imagine what would cause this, except for wrong data in the github secret itself.

Maybe on a Windows runner there might be issues with Unix newlines, but even that would be surprising to me.

**Comment by leynebe** [comment]
I mean I moved `~/config/git/credentials` to `~/config/git/credentials.back` and reran the ci. I agree it's very weird, but it kept failing before and worked after this fix.

**Comment by m-ou-se** [comment]
Unlike the GitHub-hosted runners, self-hosted runners keep their state. I don't think `setup-git-credentials` takes that into account, and instead just assumes to start with a clean state every time. Running this action multiple times will just append the secret over and over again to the file.

**Comment by leynebe** [comment]
I was wondering something similar regarding the multiple lines. I'm not sure if this is intended, but in the code I'm seeing the `a` flag being used on `fs.writeFile`. (https://github.com/fusion-engineering/setup-git-credentials/blob/master/src/main.ts#L19)
Assuming I have the right docs (https://nodejs.org/api/fs.html#file-system-flags) this means new values are appended to the existing file.
Would it be better to replace the existing value instead? I think this would be flag `w`?

**Comment by m-ou-se** [comment]
We should only add things that aren't already there. But right now this action simply isn't designed to be used in a self-hosted runner where the state is kept between runs.

**Comment by de-vri-es** [comment]
Ah, I see, we also weren't adding a trailing newline, so that's why all the credentials ended up duplicated on a single line.

#12 should fix this.
