### ISSUE TITLE
take dollar sign out

### ISSUE THREAD

**Issue by lattice0** [de-vri-es/setup-git-credentials#13]
https://$username:$token@github.com/

take the dolar signs off or at least put a warning, I was using with the dollar sign

also should be nice to say to people that they should create a secrets with this variable

thanks anyway for the nice action

**Comment by de-vri-es** [comment]
Well, the README does say this in the first paragraph:
> It is highly recommended to store the credentials in a secret and pass the secret to the action, rather than hard-coding the credentials in the configuration file.

And dollar signs are widely used to indicate variables to be replaced.

Thank you for the feedback, but I see no immediate reason to change the documentation at this moment. If you have concrete suggestions to make the documentation more clear, feel free to open a pull request though.

**Comment by lattice0** [comment]
I stored them in the GitHub secret, it's just that it makes no sense that the GitHub secret contain dollar signs

Enviado via ProtonMail móvel

-------- Mensagem Original --------
Ativo 9 de nov. de 2021 16:44, Maarten de Vries escreveu:
