### ISSUE TITLE
Repository not found : fusion-engineering/setup-git-credentials

### ISSUE THREAD

**Issue by sshcheung** [de-vri-es/setup-git-credentials#15]
Hi, our workflows started failing with the above error this afternoon.  The fusion-engineering/setup-git-credentials redirects here. Just wondering if the repository was moved/renamed today or if this is a case of github action runners no longer following redirects?

**Comment by m-ou-se** [comment]
We moved it earlier today, expecting that redirection would just work. Apparently it does not.

@de-vri-es Should we just move it back?

**Comment by de-vri-es** [comment]
Ugh, that's a shame. I've uploaded the same repository at the old location. I guess I'll keep pushing tags to both locations for a couple of years :')

**Comment by sshcheung** [comment]
Many thanks Mara and Maarten, my workflow is working again.

**Comment by de-vri-es** [comment]
I've also opened a ticket with github support by the way. If this gets fixed on GitHub's side, I'll move the repository back and forth again to turn it into a redirect.
