### ISSUE TITLE
Latest changes not applied to the `v2` tag.

### ISSUE THREAD

**Issue by heathsnow** [de-vri-es/setup-git-credentials#26]
## Description

I set my action to use `de-vri-es/setup-git-credentials@v2` but this isn't picking up the latest changes. The expectation I have when setting my versioning this way is that my action will use all Minor and Revision updates of the Major version.

### Solution

Update the release process so that all revision changes with the same Major version get applied to the `v#` tag as well.

**Comment by de-vri-es** [comment]
Hmm, the `v2` tag is pointing to the same commit as `v2.0.10`. What else can I do?

The remaining unreleased changes on the main branch are just CI additions, so they don't matter for the released version.
