### ISSUE TITLE
Error: Unable to resolve action. Repository not found: fusion-engineering/setup-git-credentials

### ISSUE THREAD

**Issue by agdebroisemns** [de-vri-es/setup-git-credentials#32]
Hi folks,
Our workflows started failing yesterday with the above error...
Can you help?
TIA!
![image](https://github.com/user-attachments/assets/560d9cc1-22d1-463d-a102-05cc6e18e00f)

Same as older issue https://github.com/de-vri-es/setup-git-credentials/issues/15?

**Comment by de-vri-es** [comment]
Yes, I think so. We moved the repository back and forth to get the old URL to redirect to this one properly. When I tested using an action that moved between owners it did keep working :/ 

However, I recommend to update to the new address: `de-vri-es/setup-git-credentials`. That should fix it immediately.

**Comment by agdebroisemns** [comment]
Thank you for the quick response and fix.
For the long term solution, yeah, we will be moving to the new address.
