### ISSUE TITLE
Cannot find module './utils'

### ISSUE THREAD

**Issue by ingshtrom** [de-vri-es/setup-git-credentials#8]
Dependabot upgraded all of our code to use `fusion-engineering/setup-git-credentials@v2.0.4`. We were using `v2.0.3` prior to this. Now we get this error when using it in the same way as before. Reverting has fixed our issue.

<img width="1229" alt="CleanShot 2020-12-18 at 14 08 51@2x" src="https://user-images.githubusercontent.com/571756/102651595-ba1e1200-4164-11eb-8581-d66b26037ca2.png">

**Comment by de-vri-es** [comment]
Thanks for reporting this! It appears I forgot to add some required distribution files. It should be fixed now in 2.0.5.
